module.exports = {
	'events': {
		'sku': 'TEXT',
		'key': 'TEXT',
		'program': 'TEXT',
		'name': 'TEXT',
		'loc_venue': 'TEXT',
		'loc_address1': 'TEXT',
		'loc_address2': 'TEXT',
		'loc_city': 'TEXT',
		'loc_region': 'TEXT',
		'loc_postalcode': 'TEXT',
		'loc_country': 'TEXT',
		'season': 'TEXT',
		'start': 'INTEGER',
		'end': 'INTEGER',
		'divisions': 'TEXT'
	},
	'teams': {
		'number': 'TEXT',
		'program': 'TEXT',
		'team_name': 'TEXT',
		'robot_name': 'TEXT',
		'organisation': 'TEXT',
		'city': 'TEXT',
		'region': 'TEXT',
		'country': 'TEXT',
		'grade': 'TEXT',
		'is_registered': 'INTEGER'
	},
	'matches': {
		'sku': 'TEXT',
		'division': 'TEXT',
		'round': 'INTEGER',
		'instance': 'INTEGER',
		'matchnum': 'INTEGER',
		'field': 'TEXT',
		'red1': 'TEXT',
		'red2': 'TEXT',
		'red3': 'TEXT',
		'redsit': 'TEXT',
		'blue1': 'TEXT',
		'blue2': 'TEXT',
		'blue3': 'TEXT',
		'bluesit': 'TEXT',
		'redscore': 'INTEGER',
		'bluescore': 'INTEGER',
		'scored': 'INTEGER',
		'scheduled': 'INTEGER'
	},
	'rankings': {
		'sku': 'TEXT',
		'division': 'TEXT',
		'rank': 'INTEGER',
		'team': 'TEXT',
		'wins': 'INTEGER',
		'losses': 'INTEGER',
		'ties': 'INTEGER',
		'wp': 'INTEGER',
		'ap': 'INTEGER',
		'sp': 'INTEGER',
		'trsp': 'INTEGER',
		'max_score': 'INTEGER',
		'opr': 'REAL',
		'dpr': 'REAL',
		'ccwm': 'REAL'
	},
	'awards': {
		'sku': 'TEXT',
		'name': 'TEXT',
		'team': 'TEXT',
		'qualifies': 'TEXT',
		'order': 'INTEGER'
	},
	'skills': {
		'sku': 'TEXT',
		'type': 'INTEGER',
		'rank': 'INTEGER',
		'team': 'TEXT',
		'program': 'TEXT',
		'attempts': 'INTEGER',
		'score': 'INTEGER'
	}
};
